trigger:
  branches:
    include:
      - none

pool: pipepool

stages:
# ---------------- STAGE 1 ----------------
- stage: validate
  displayName: fmt & validate
  jobs:
  - job: fmt_validate
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - script: terraform fmt -recursive
      workingDirectory: '$(System.DefaultWorkingDirectory)/Envoirnment/Dev/'

    - script: terraform validate
      workingDirectory: '$(System.DefaultWorkingDirectory)/Envoirnment/Dev/'

# ---------------- STAGE 2 ----------------
- stage: plan
  displayName: terraform plan
  dependsOn: validate
  jobs:
  - job: terraform_plan
    steps:
    - task: TerraformTask@5
      displayName: terraform init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Envoirnment/Dev/'
        backendServiceArm: 'pipeline_new_infra'
        backendAzureRmResourceGroupName: 'allIndiarg'
        backendAzureRmStorageAccountName: 'allindiasa'
        backendAzureRmContainerName: 'kuchbhicontainer'
        backendAzureRmKey: 'ashu11.tfstate'

    - task: TerraformTask@5
      displayName: terraform plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: '-refresh=false -parallelism=10'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Envoirnment/Dev/'
        environmentServiceNameAzureRM: 'pipeline_new_infra'

# ---------------- STAGE 3 ----------------
- stage: approval
  displayName: manual approval
  dependsOn: plan
  jobs:
  - job: manual_validation
    pool: server
    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'anoopkushwaha509@gmail.com'
        instructions: 'Approve to apply Terraform changes'

# ---------------- STAGE 4 ----------------
- stage: apply
  displayName: terraform apply
  dependsOn: approval
  jobs:
  - job: terraform_apply
    steps:
    - task: TerraformTask@5
      displayName: terraform init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Envoirnment/Dev/'
        backendServiceArm: 'pipeline_new_infra'
        backendAzureRmResourceGroupName: 'allIndiarg'
        backendAzureRmStorageAccountName: 'allindiasa'
        backendAzureRmContainerName: 'kuchbhicontainer'
        backendAzureRmKey: 'ashu11.tfstate'

    - task: TerraformTask@5
      displayName: terraform apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: '-auto-approve'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Envoirnment/Dev/'
        environmentServiceNameAzureRM: 'pipeline_new_infra'
